 
// permissions.constants.ts
export const PERMISSIONS = {
  // Admin permissions
  CREATE_EVENT: 'CREATE_EVENT',
  APPROVE_EVENT: 'APPROVE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_ALL_EVENTS: 'VIEW_ALL_EVENTS',
  VIEW_ALL_REPORTS: 'VIEW_ALL_REPORTS',
  
  // Manager permissions
  CREATE_DEPARTMENT_EVENT: 'CREATE_DEPARTMENT_EVENT',
  APPROVE_DEPARTMENT_EVENT: 'APPROVE_DEPARTMENT_EVENT',
  VIEW_DEPARTMENT_EVENTS: 'VIEW_DEPARTMENT_EVENTS',
  VIEW_DEPARTMENT_REPORTS: 'VIEW_DEPARTMENT_REPORTS',
  
  // Communication Manager specific
  MANAGE_COMMUNICATION_EVENTS: 'MANAGE_COMMUNICATION_EVENTS',
  ASSIGN_CAMERA_MAN: 'ASSIGN_CAMERA_MAN',
  
  // Staff/Communication Expert permissions
  CREATE_COMMUNICATION_EVENT: 'CREATE_COMMUNICATION_EVENT',
  VIEW_COMMUNICATION_EVENTS: 'VIEW_COMMUNICATION_EVENTS',
  
  // Employee permissions
  VIEW_EVENTS: 'VIEW_EVENTS',
  VIEW_DEPARTMENT_DATA: 'VIEW_DEPARTMENT_DATA'
} as const;